apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: <email>
    privateKeySecretRef:
      name: letsencrypt-dns
    solvers:
      - dns01:
          azureDNS:
            subscriptionID: "<subscription-id>"
            resourceGroupName: "<resource-group>"
            hostedZoneName: "<hosted-zone>"
            environment: AzurePublicCloud
            managedIdentity:
              clientID: "<client-id>"
