# Source: external-secrets/templates/cluster-secret-store.yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-cluster-secret-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      # URL of your vault instance, see: https://docs.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates
      vaultUrl: "https://<kv-name>.vault.azure.net/"
      serviceAccountRef:
        name: external-secrets